from os import environ

_ = environ.get

TWITTER_API_KEY=_("TWITTER_API_KEY", "")
TWITTER_API_SECRET_KEY=_("TWITTER_API_SECRET_KEY", "")
TWITTER_BEARER_TOKEN=_("TWITTER_BEARER_TOKEN", "")
TWITTER_ACCESS_TOKEN=_("TWITTER_ACCESS_TOKEN", "")
TWITTER_ACCESS_TOKEN_SECRET=_("TWITTER_ACCESS_TOKEN_SECRET", "")