import ast

from datetime import date, timedelta
from os import environ

_ = environ.get

TWITTER_NOTIFICATION=_("TWITTER_NOTIFICATION", False)
TWITTER_API_KEY=_("TWITTER_API_KEY", "")
TWITTER_API_SECRET_KEY=_("TWITTER_API_SECRET_KEY", "")
TWITTER_BEARER_TOKEN=_("TWITTER_BEARER_TOKEN", "")
TWITTER_ACCESS_TOKEN=_("TWITTER_ACCESS_TOKEN", "")
TWITTER_ACCESS_TOKEN_SECRET=_("TWITTER_ACCESS_TOKEN_SECRET", "")
DISCORD_NOTIFICATION=_("DISCORD_NOTIFICATION", False)
DISCORD_WEBHOOK_URL=_("DISCORD_WEBHOOK_URL", "")
PRIME_TIME=_("PRIME_TIME", ["09:00", "19:00"])
SCRAPPING_TIME=_("SCRAPPING_TIME", ["00:30", "06:45", "16:45"])
GENERATE_TIME=_("GENERATE_TIME", ["01:00", "07:30", "17:30"])
DATA_DIR=_("DATA_DIR", "./data")
WEBHOOK_DISCORD_URL=_("WEBHOOK_DISCORD_URL", "")
HEADERS = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
}

DISCORD_NOTIFICATION=True if DISCORD_NOTIFICATION=="True" or DISCORD_NOTIFICATION=="true" else DISCORD_NOTIFICATION
TWITTER_NOTIFICATION=True if TWITTER_NOTIFICATION=="True" or TWITTER_NOTIFICATION=="true" else TWITTER_NOTIFICATION
PRIME_TIME = ast.literal_eval(PRIME_TIME) if type(PRIME_TIME) == str else PRIME_TIME
SCRAPPING_TIME = ast.literal_eval(SCRAPPING_TIME) if type(SCRAPPING_TIME) == str else SCRAPPING_TIME
