import ast

from datetime import date, timedelta
from os import environ

_ = environ.get

TWITTER_NOTIFICATION=_("TWITTER_NOTIFICATION", False)
TWITTER_API_KEY=_("TWITTER_API_KEY", "")
TWITTER_API_SECRET_KEY=_("TWITTER_API_SECRET_KEY", "")
TWITTER_BEARER_TOKEN=_("TWITTER_BEARER_TOKEN", "")
TWITTER_ACCESS_TOKEN=_("TWITTER_ACCESS_TOKEN", "")
TWITTER_ACCESS_TOKEN_SECRET=_("TWITTER_ACCESS_TOKEN_SECRET", "")
DISCORD_NOTIFICATION=_("DISCORD_NOTIFICATION", False)
DISCORD_WEBHOOK_URL=_("DISCORD_WEBHOOK_URL", "")
PRIME_TIME=_("PRIME_TIME", ["01:00", "09:00", "13:00", "19:00"])
SCRAPPING_TIME=_("SCRAPPING_TIME", ["00:45", "07:00", "08:45", "12:45", "18:45", "21:00"])
DATA_DIR=_("DATA_DIR", "./data")

DISCORD_NOTIFICATION=True if DISCORD_NOTIFICATION=="True" or DISCORD_NOTIFICATION=="true" else DISCORD_NOTIFICATION
TWITTER_NOTIFICATION=True if TWITTER_NOTIFICATION=="True" or TWITTER_NOTIFICATION=="true" else TWITTER_NOTIFICATION
PRIME_TIME = ast.literal_eval(PRIME_TIME) if type(PRIME_TIME) == str else PRIME_TIME
SCRAPPING_TIME = ast.literal_eval(SCRAPPING_TIME) if type(SCRAPPING_TIME) == str else SCRAPPING_TIME